-- AGREGAR COLUMNA MONTO DE CUOTAS EN GRUPO
IF NOT EXISTS (SELECT * 
               FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_NAME = 'Grupo' 
               AND COLUMN_NAME = 'MontoCuota_N')
BEGIN
    ALTER TABLE Grupo
    ADD MontoCuota_N numeric(18,2);
END
GO

--ELIMINAR CONSTRAINT DE CANTIDAD DE CUOTAS
IF EXISTS (SELECT * 
           FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
           WHERE CONSTRAINT_NAME = 'CK_CantidadCuotas_i' 
           AND TABLE_NAME = 'Grupo')
BEGIN
    ALTER TABLE Grupo
    DROP CONSTRAINT CK_CantidadCuotas_i;
END
GO

--CAMBIAR ESTADO GRUPO
ALTER TABLE Grupo
DROP CONSTRAINT CK__Grupo__Estado_c__60A75C0F;

IF NOT EXISTS (SELECT * 
               FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE CONSTRAINT_NAME = 'CK_GrupoEstadoC' 
               AND TABLE_NAME = 'Grupo')
BEGIN
    ALTER TABLE Grupo
    ADD CONSTRAINT CK_GrupoEstadoC
    CHECK ([Estado_c] IN ('E', 'A', 'C', 'F', 'T'));
END

--MODIFICAR EL TIPO DE DATO DE DOCUMENTOS
ALTER TABLE Documento
ALTER COLUMN FileDocIdentidad_by VARBINARY(MAX);

ALTER TABLE Documento
ALTER COLUMN FileAntecedentesPenales_by VARBINARY(MAX);

ALTER TABLE Documento
ALTER COLUMN FileReciboLuzAgua_by VARBINARY(MAX);

ALTER TABLE Documento
ALTER COLUMN FileEquifax_by VARBINARY(MAX);